  apache:
    build: .
    container_name: lamp_apache
    volumes:
      - ./lamp-studenti/studenti:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql
services:
  apache:
    build: ./apache
    container_name: lamp_apache
    volumes:
      - ./studenti:/var/www/html
    ports:
      - "8080:80"
    version: '3.8'
    services:
      mysql:
        image: mysql:latest
        container_name: mysql_contact_form
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: contact_form
        ports:
          - "3306:3306"
        volumes:
          - db_data:/var/lib/mysql
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    volumes:
      db_data: